DROP TABLE TBR_ENQUENTE;

CREATE TABLE TBR_ENQUENTE(
   id number generated by default as identity,
   nome varchar2(100),
   categoria varchar2(100),
   primary key(id) 
);

DROP TABLE TBR_PERGUNTA;

CREATE TABLE TBR_PERGUNTA(
    id number generated by default as identity,
    texto varchar2(500),
    tipo number(1),
    numero number(2),
    id_enquente number,
    primary key(id),
    foreign key(id_enquente) references TBR_ENQUENTE(id)
);

DROP TABLE TBR_OPCOES;

CREATE TABLE TBR_OPCOES(
    alternativa varchar2(100),
    rotulo number(2),
    id_pergunta number,
    foreign key(id_pergunta) references TBR_PERGUNTA(id)
); 

DROP TABLE TBR_PESSOA;

CREATE TABLE TBR_PESSOA(
    id number generated by default as identity,
    nome varchar2(100),
    idade number(2),
    municipio varchar2(50),
    escolaridade varchar2(50),
    sexo varchar2(20),
    primary key(id)
); 

DROP TABLE TBR_RESPOSTA;

CREATE TABLE TBR_RESPOSTA(
    texto varchar2(300),
    datahora timestamp,
    id_pessoa number,
    id_pergunta number,
    foreign key(id_pessoa) references tbr_pessoa(id),
    foreign key(id_pergunta) references tbr_pergunta(id)
);

